2025-03-26 15:49:36,836 - custodian.policy - DEBUG - Running policy:listAllTransfer resource:huaweicloud.lts-transfer region:default c7n:0.9.43
2025-03-26 15:49:37,967 - custodian.output - DEBUG - metric:PolicyException Count:1 policy:listalltransfer restype:huaweicloud.lts-transfer
2025-03-26 15:49:37,970 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/root/cloud-custodian/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/root/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 324, in resources
    resources = self._fetch_resources(q)
  File "/root/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 343, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
  File "/root/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 230, in get_resources
    return self.query.filter(self.manager, **query)
  File "/root/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 51, in filter
    resources = self._pagination_limit_offset(m, enum_op, path)
  File "/root/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/query.py", line 89, in _pagination_limit_offset
    data['tag_resource_type'] = m.tag_resource_type
AttributeError: type object 'resource_type' has no attribute 'tag_resource_type'
2025-03-26 15:57:55,482 - custodian.policy - DEBUG - Running policy:listAllTransfer resource:huaweicloud.lts-transfer region:default c7n:0.9.43
2025-03-26 15:57:56,534 - custodian.resources.transfer - DEBUG - Filtered from 2 to 1 transfer
2025-03-26 15:57:56,536 - custodian.policy - INFO - policy:listAllTransfer resource:huaweicloud.lts-transfer region: count:1 time:1.05
2025-03-26 15:57:56,538 - custodian.output - DEBUG - metric:ResourceCount Count:1 policy:listalltransfer restype:huaweicloud.lts-transfer scope:policy
